In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist         # библиотека базы выборок Mnist
from tensorflow import keras
from tensorflow.keras.layers import Dense, Flatten

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# стандартизация входных данных
x_train = x_train / 255
x_test = x_test / 255

y_train_cat = keras.utils.to_categorical(y_train, 10)
y_test_cat = keras.utils.to_categorical(y_test, 10)

model = keras.Sequential([
    Flatten(input_shape=(28, 28, 1)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

print(model.summary())     
# вывод структуры НС в консоль

# оптимизатор Adam, шаг сходимости = 0,001
myAdam = keras.optimizers.Adam(learning_rate=0.001)

model.compile(optimizer=myAdam,
             loss='categorical_crossentropy',
             metrics=['accuracy'])

model.fit(x_train, y_train_cat, batch_size=32, epochs=5, validation_split=0.2)

model.evaluate(x_test, y_test_cat)

n = 1
x = np.expand_dims(x_test[n], axis=0)
res = model.predict(x)
print( res )
print( np.argmax(res) )

# Распознавание всей тестовой выборки
pred = model.predict(x_test)
pred = np.argmax(pred, axis=1)

print(pred.shape)

print(pred[:30])
print(y_test[:30])


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/5
1500/1500 [==============================] - 13s 7ms/step - loss: 0.2873 - accuracy: 0.9189 - val_loss: 0.1551 - val_accuracy: 0.9549
Epoch 2/5
1500/1500 [==============================] - 8s 6ms/step - loss: 0.1246 - accuracy: 0.9639 - val_loss: 0.1137 - val_accuracy: 0.9678
Epoch 3/5
1500/1500 [=

In [30]:
# оптимизатор RMSProp, шаг сходимости = 0,00001
myRMS = keras.optimizers.RMSprop(learning_rate=0.00001)
model.compile(optimizer=myRMS,
             loss='categorical_crossentropy',
             metrics=['accuracy'])

model.fit(x_train, y_train_cat, batch_size=32, epochs=5, validation_split=0.2)

model.evaluate(x_test, y_test_cat)

n = 1
x = np.expand_dims(x_test[n], axis=0)
res = model.predict(x)
print( res )
print( np.argmax(res) )

# Распознавание всей тестовой выборки
pred = model.predict(x_test)
pred = np.argmax(pred, axis=1)

print(pred.shape)

print(pred[:30])
print(y_test[:30])

Epoch 1/5
1500/1500 [==============================] - 7s 5ms/step - loss: 0.0062 - accuracy: 0.9987 - val_loss: 0.0811 - val_accuracy: 0.9797
Epoch 2/5
1500/1500 [==============================] - 7s 4ms/step - loss: 0.0062 - accuracy: 0.9986 - val_loss: 0.0812 - val_accuracy: 0.9797
Epoch 3/5
1500/1500 [==============================] - 7s 4ms/step - loss: 0.0062 - accuracy: 0.9986 - val_loss: 0.0813 - val_accuracy: 0.9797
Epoch 4/5
1500/1500 [==============================] - 6s 4ms/step - loss: 0.0062 - accuracy: 0.9987 - val_loss: 0.0813 - val_accuracy: 0.9797
Epoch 5/5
1/1 [==============================] - 0s 67ms/step
[[1.5934338e-14 2.9014927e-08 1.0000000e+00 3.0264855e-09 4.9671984e-22
  4.0759889e-11 8.9394887e-13 8.9523641e-22 4.1198999e-11 1.6507182e-20]]
2
313/313 [==============================] - 1s 2ms/step
(10000,)
[7 2 1 0 4 1 4 9 6 9 0 6 9 0 1 5 9 7 3 4 9 6 6 5 4 0 7 4 0 1]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4 9 6 6 5 4 0 7 4 0 1]


In [7]:
# оптимизатор стохастический градиентный алгоритм с моментами Нестерова, шаг сходимости = 0,001
mySGD = keras.optimizers.SGD(learning_rate=0.0001, momentum=0.001, nesterov=True)
model.compile(optimizer=myAdam,
             loss='categorical_crossentropy',
             metrics=['accuracy'])

model.fit(x_train, y_train_cat, batch_size=32, epochs=5, validation_split=0.2)

model.evaluate(x_test, y_test_cat)

n = 1
x = np.expand_dims(x_test[n], axis=0)
res = model.predict(x)
print( res )
print( np.argmax(res) )

# Распознавание всей тестовой выборки
pred = model.predict(x_test)
pred = np.argmax(pred, axis=1)

print(pred.shape)

print(pred[:30])
print(y_test[:30])

Epoch 1/5
1500/1500 [==============================] - 10s 6ms/step - loss: 0.0017 - accuracy: 0.9994 - val_loss: 0.1390 - val_accuracy: 0.9774
Epoch 2/5
1500/1500 [==============================] - 8s 5ms/step - loss: 0.0047 - accuracy: 0.9986 - val_loss: 0.1366 - val_accuracy: 0.9774
Epoch 3/5
1500/1500 [==============================] - 7s 5ms/step - loss: 0.0024 - accuracy: 0.9993 - val_loss: 0.1395 - val_accuracy: 0.9778
Epoch 4/5
1500/1500 [==============================] - 8s 5ms/step - loss: 0.0040 - accuracy: 0.9988 - val_loss: 0.1615 - val_accuracy: 0.9750
Epoch 5/5
1/1 [==============================] - 0s 60ms/step
[[1.2957939e-25 2.3256042e-13 1.0000000e+00 5.8173905e-17 1.2924050e-36
  1.6559539e-19 6.3465432e-18 0.0000000e+00 1.5519574e-17 1.6960706e-27]]
2
313/313 [==============================] - 1s 2ms/step
(10000,)
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4 9 6 6 5 4 0 7 4 0 1]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4 9 6 6 5 4 0 7 4 0 1]
